### ISSUE TITLE
Crash on loading soundfont.

### ISSUE THREAD

**Issue by Tweak4141** [PolyMeilex/Neothesia#32]
```
PS C:\Users\Talos\Downloads> $env:RUST_BACKTRACE="full"
PS C:\Users\Talos\Downloads> ./neothesia
[2023-02-09T06:30:13Z INFO  neothesia::scene::menu_scene::iced_menu] File path = "E:\\Dev\\Orpheus GM Current Release\\Demos\\J. Williams - Star Wars OST.mid"
[2023-02-09T06:30:19Z INFO  neothesia::scene::menu_scene::iced_menu] Font path = "E:\\Dev\\Orpheus GM Current Release\\Orpheus_1.047e.sf2"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src\output_manager\synth_backend.rs:107:65
stack backtrace:
   0:     0x7ff6f2dd6c52 - <unknown>
   1:     0x7ff6f2df027b - <unknown>
   2:     0x7ff6f2dd35fa - <unknown>
   3:     0x7ff6f2dd699b - <unknown>
   4:     0x7ff6f2dd9329 - <unknown>
   5:     0x7ff6f2dd8faa - <unknown>
   6:     0x7ff6f2dd9bb1 - <unknown>
   7:     0x7ff6f2dd993d - <unknown>
   8:     0x7ff6f2dd767f - <unknown>
   9:     0x7ff6f2dd9600 - <unknown>
  10:     0x7ff6f2e1eee5 - <unknown>
  11:     0x7ff6f2e1f1f3 - <unknown>
  12:     0x7ff6f28bead4 - <unknown>
  13:     0x7ff6f2870724 - <unknown>
  14:     0x7ff6f28b505d - <unknown>
  15:     0x7ff6f2860421 - <unknown>
  16:     0x7ff6f289de72 - <unknown>
  17:     0x7ff6f286eea0 - <unknown>
  18:     0x7ff6f27b0aa8 - <unknown>
  19:     0x7ff6f27b426c - <unknown>
  20:     0x7ff6f27b265b - <unknown>
  21:     0x7ff6f27b1cce - <unknown>
  22:     0x7ff6f27b3b79 - <unknown>
  23:     0x7ff6f27b10ee - <unknown>
  24:     0x7ff6f27ac155 - <unknown>
  25:     0x7ffb2b63e7e8 - CallWindowProcW
  26:     0x7ffb2b63e36c - DispatchMessageW
  27:     0x7ffb2b650c23 - SendMessageTimeoutW
  28:     0x7ffb2d5f0ef4 - KiUserCallbackDispatcher
  29:     0x7ffb2acb1704 - NtUserDispatchMessage
  30:     0x7ffb2b63e27a - DispatchMessageW
  31:     0x7ff6f27aadc7 - <unknown>
  32:     0x7ff6f277ea21 - <unknown>
  33:     0x7ff6f2785b39 - <unknown>
  34:     0x7ff6f2773ee6 - <unknown>
  35:     0x7ff6f27ad14c - <unknown>
  36:     0x7ff6f2dcc97e - <unknown>
  37:     0x7ff6f27861ec - <unknown>
  38:     0x7ff6f2df92cc - <unknown>
  39:     0x7ffb2bce7614 - BaseThreadInitThunk
  40:     0x7ffb2d5a26a1 - RtlUserThreadStart
PS C:\Users\Talos\Downloads>
```
The soundfont, and midi can be downloaded here:
https://musical-artifacts.com/artifacts/1213

This issue seems to only occur with large soundfonts.

**Comment by PolyMeilex** [comment]
Looks like it uses non spec conforming values for it's generators. Does this build help https://github.com/PolyMeilex/Neothesia/actions/runs/4138078601 ?

**Comment by Tweak4141** [comment]
> Looks like it uses non spec conforming values for it's generators. Does this build help https://github.com/PolyMeilex/Neothesia/actions/runs/4138078601 ?

Hey, it did not crash this time on startup. However, a new issue has appeared.
```
PS C:\Users\Talos\Downloads> $env:RUST_BACKTRACE="full"
PS C:\Users\Talos\Downloads> ./neothesia
[2023-02-09T23:09:40Z INFO  neothesia::scene::menu_scene::iced_menu] File path = "E:\\Dev\\Orpheus GM Current Release\\Demos\\J. Williams - Star Wars OST.mid"
[2023-02-09T23:09:46Z INFO  neothesia::scene::menu_scene::iced_menu] Font path = "E:\\Dev\\Orpheus GM Current Release\\Orpheus_1.047e.sf2"
thread 'main' panicked at 'index out of bounds: the len is 60 but the index is 60', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\oxisynth-0.0.3\src\core\synth\soundfont\instrument.rs:102:21
stack backtrace:
   0:     0x7ff7dcfd3a52 - <unknown>
   1:     0x7ff7dcfed1ab - <unknown>
   2:     0x7ff7dcfd07fa - <unknown>
   3:     0x7ff7dcfd379b - <unknown>
   4:     0x7ff7dcfd60c9 - <unknown>
   5:     0x7ff7dcfd5d4b - <unknown>
   6:     0x7ff7dcfd6961 - <unknown>
   7:     0x7ff7dcfd66ee - <unknown>
   8:     0x7ff7dcfd446f - <unknown>
   9:     0x7ff7dcfd63a0 - <unknown>
  10:     0x7ff7dd01c265 - <unknown>
  11:     0x7ff7dd01c3d7 - <unknown>
  12:     0x7ff7dcaff81d - <unknown>
  13:     0x7ff7dcaef3f9 - <unknown>
  14:     0x7ff7dca81168 - <unknown>
  15:     0x7ff7dcad821f - <unknown>
  16:     0x7ff7dca441b7 - <unknown>
  17:     0x7ff7dca89d71 - <unknown>
  18:     0x7ff7dca69d31 - <unknown>
  19:     0x7ff7dcabe522 - <unknown>
  20:     0x7ff7dca421e0 - <unknown>
  21:     0x7ff7dc9aa1e9 - <unknown>
  22:     0x7ff7dc9b1275 - <unknown>
  23:     0x7ff7dc9adc9c - <unknown>
  24:     0x7ff7dc9ad642 - <unknown>
  25:     0x7ff7dc9ab0b7 - <unknown>
  26:     0x7ff7dc9b0b0b - <unknown>
  27:     0x7ff7dc9ac76d - <unknown>
  28:     0x7ffb2b63e7e8 - CallWindowProcW
  29:     0x7ffb2b63e36c - DispatchMessageW
  30:     0x7ffb2b650c23 - SendMessageTimeoutW
  31:     0x7ffb2d5f0ef4 - KiUserCallbackDispatcher
  32:     0x7ffb2acb1704 - NtUserDispatchMessage
  33:     0x7ffb2b63e27a - DispatchMessageW
  34:     0x7ff7dc9aae86 - <unknown>
  35:     0x7ff7dc97c9b1 - <unknown>
  36:     0x7ff7dc97e466 - <unknown>
  37:     0x7ff7dc9b13f6 - <unknown>
  38:     0x7ff7dc97eb3c - <unknown>
  39:     0x7ff7dcfc995e - <unknown>
  40:     0x7ff7dc97eb1c - <unknown>
  41:     0x7ff7dcff61cc - <unknown>
  42:     0x7ffb2bce7614 - BaseThreadInitThunk
  43:     0x7ffb2d5a26a1 - RtlUserThreadStart
  ```

**Comment by Tweak4141** [comment]
This issue still appears with another large soundfont.

```
[2023-02-09T23:13:33Z INFO  neothesia::scene::menu_scene::iced_menu] File path = "E:\\Dev\\Orpheus GM Current Release\\Demos\\J. Williams - Star Wars OST.mid"
[2023-02-09T23:13:42Z INFO  neothesia::scene::menu_scene::iced_menu] Font path = "E:\\Dev\\sf\\Musyng.sf2"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src\output_manager\synth_backend.rs:107:65
stack backtrace:
   0:     0x7ff79fc23a52 - <unknown>
   1:     0x7ff79fc3d1ab - <unknown>
   2:     0x7ff79fc207fa - <unknown>
   3:     0x7ff79fc2379b - <unknown>
   4:     0x7ff79fc260c9 - <unknown>
   5:     0x7ff79fc25d4b - <unknown>
   6:     0x7ff79fc26961 - <unknown>
   7:     0x7ff79fc266ee - <unknown>
   8:     0x7ff79fc2446f - <unknown>
   9:     0x7ff79fc263a0 - <unknown>
  10:     0x7ff79fc6c265 - <unknown>
  11:     0x7ff79fc6c766 - <unknown>
  12:     0x7ff79f72858d - <unknown>
  13:     0x7ff79f6941b7 - <unknown>
  14:     0x7ff79f6d9d71 - <unknown>
  15:     0x7ff79f6b9d31 - <unknown>
  16:     0x7ff79f70e522 - <unknown>
  17:     0x7ff79f6921e0 - <unknown>
  18:     0x7ff79f5fa1e9 - <unknown>
  19:     0x7ff79f601275 - <unknown>
  20:     0x7ff79f5fdc9c - <unknown>
  21:     0x7ff79f5fd642 - <unknown>
  22:     0x7ff79f5fb0b7 - <unknown>
  23:     0x7ff79f600b0b - <unknown>
  24:     0x7ff79f5fc76d - <unknown>
  25:     0x7ffb2b63e7e8 - CallWindowProcW
  26:     0x7ffb2b63e36c - DispatchMessageW
  27:     0x7ffb2b650c23 - SendMessageTimeoutW
  28:     0x7ffb2d5f0ef4 - KiUserCallbackDispatcher
  29:     0x7ffb2acb1704 - NtUserDispatchMessage
  30:     0x7ffb2b63e27a - DispatchMessageW
  31:     0x7ff79f5fae86 - <unknown>
  32:     0x7ff79f5cc9b1 - <unknown>
  33:     0x7ff79f5ce466 - <unknown>
  34:     0x7ff79f6013f6 - <unknown>
  35:     0x7ff79f5ceb3c - <unknown>
  36:     0x7ff79fc1995e - <unknown>
  37:     0x7ff79f5ceb1c - <unknown>
  38:     0x7ff79fc461cc - <unknown>
  39:     0x7ffb2bce7614 - BaseThreadInitThunk
  40:     0x7ffb2d5a26a1 - RtlUserThreadStart
  ```
  The source file is here:
  http://www.synthfont.com/SoundFonts/Musyng.sfpack
  I unpacked it and will add link when uploaded.

**Comment by PolyMeilex** [comment]
> Hey, it did not crash this time on startup. However, a new issue has appeared.

Oh yeah, that's my bad, ignoring validations made it panic later down the line, did not think about that.

> I unpacked it and will add link when uploaded.

Thanks, if you could link fonts that are not working it would be nice, soundfounts are kinda wild west, spec is just a suggestion a lot of the time.

Meanwhile, if you just want to get a working synthesizer you could use a fluidsynth based build: https://github.com/PolyMeilex/Neothesia/actions/runs/4139409659 instead of my implementation of the spec.

**Comment by Tweak4141** [comment]
> Oh yeah, that's my bad, ignoring validations made it panic later down the line, did not think about that.
I see, thanks for the quick response.
> Thanks, if you could link fonts that are not working it would be nice, soundfounts are kinda wild west, spec is just a suggestion a lot of the time.

Here's the link, https://cdn.talosbot.xyz/sf-cdn/Musyng.sf2
If I do find any more incompatible soundfonts I'll link them here.

> Meanwhile, if you just want to get a working synthesizer you could use a fluidsynth based build: https://github.com/PolyMeilex/Neothesia/actions/runs/4139409659 instead of my implementation of the spec.
Thanks for this, your quick responses are definitely appreciated.

**Comment by luzpaz** [comment]
Is this issue still present ?

**Comment by PolyMeilex** [comment]
Sorry, for the delay, 
I got both of those fonts running, this will land in 0.2.

Orpheus sounds a bit off, most likely because I don't support non-standard generators it uses.
Musyng works flawlessly tho:

https://github.com/PolyMeilex/OxiSynth/assets/20758186/e1d1c3c1-0869-4a8f-96c9-6f16a56767cb


Not closing yet, as this will require soundfont-rs and OxiSynth releases first

**Comment by Tweak4141** [comment]
Alright, thank you for your work towards this!
