### ISSUE TITLE
Can't run Neothesia on Linux Mint / Ubuntu 18.04

### ISSUE THREAD

**Issue by ivy-rew** [PolyMeilex/Neothesia#8]
The default neothesia package did not run on my machine, as I use Linux Mint 19.x which relies upon Ubuntu 18.04
I faced these errors:
`lordeagle@le-T450s:~/Downloads$ ./neothesia 
./neothesia: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./neothesia)`

However, having forked this repo and let the build run on a 'ubuntu-18.04' node I get a copy that can be run. 
https://github.com/ivy-rew/Neothesia/actions/runs/1008613870

Now, I get the following error. Any ideas what's missing?

```lordeagle@le-T450s:~/Downloads$ ./neothesia 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AdapterRequest', src/lib.rs:52:61
stack backtrace:
   0:     0x565349af3e00 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x565349af3e00 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x565349af3e00 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x565349af3e00 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x565349b1767f - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x565349af1295 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x565349af5edb - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x565349af5edb - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x565349af5edb - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x565349af59ad - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x565349af64ed - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:591:17
  11:     0x565349af6087 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
  12:     0x565349af429c - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x565349af5fe9 - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  14:     0x565349328611 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  15:     0x565349328703 - core::result::unwrap_failed::hcbdf25d28ce8f0ca
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/result.rs:1355:5
  16:     0x5653493c30c3 - neothesia::init::hf9facb0026966c11
  17:     0x56534938e2bf - neothesia::main::hca33bbc48aef2a0c
  18:     0x56534939cb83 - std::sys_common::backtrace::__rust_begin_short_backtrace::h14fb5189f438c54d
  19:     0x56534939cb99 - std::rt::lang_start::{{closure}}::h2ba87cd5fa13a1fa
  20:     0x565349af69ea - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc4354216bf39217c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
  21:     0x565349af69ea - std::panicking::try::do_call::hb68eb312780385cf
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  22:     0x565349af69ea - std::panicking::try::h22b8e08595060b8b
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  23:     0x565349af69ea - std::panic::catch_unwind::hc64f1a6a0e71b1fc
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  24:     0x565349af69ea - std::rt::lang_start_internal::h4461fc58637f04f8
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
  25:     0x56534938e532 - main
  26:     0x7f7edac15bf7 - __libc_start_main
  27:     0x565349328d8a - _start
  28:                0x0 - <unknown>
lordeagle@le-T450s:~/Downloads$ neofetch
MMMMMMMMMMMMMMMMMMMMMMMMMmds+.        lordeagle@le-T450s 
MMm----::-://////////////oymNMd+`     ------------------ 
MMd      /++                -sNMd:    OS: Linux Mint 19.3 Tricia x86_64 
MMNso/`  dMM    `.::-. .-::.` .hMN:   Host: 20BWS02D00 ThinkPad T450s 
ddddMMh  dMM   :hNMNMNhNMNMNh: `NMm   Kernel: 5.4.0-77-generic 
    NMm  dMM  .NMN/-+MMM+-/NMN` dMM   Uptime: 9 days, 11 hours, 4 mins 
    NMm  dMM  -MMm  `MMM   dMM. dMM   Packages: 2785 
    NMm  dMM  -MMm  `MMM   dMM. dMM   Shell: bash 4.4.20 
    NMm  dMM  .mmd  `mmm   yMM. dMM   Resolution: 1920x1080 
    NMm  dMM`  ..`   ...   ydm. dMM   DE: Cinnamon 4.4.8 
    hMM- +MMd/-------...-:sdds  dMM   WM: Mutter (Muffin) 
    -NMm- :hNMNNNmdddddddddy/`  dMM   WM Theme: Mint-Y-Dark-Sand (Mint-Y) 
     -dMNs-``-::::-------.``    dMM   Theme: Mint-Y-Darker-Grey [GTK2/3] 
      `/dMNmy+/:-------------:/yMMM   Icons: Mint-Y-Grey [GTK2/3] 
         ./ydNMMMMMMMMMMMMMMMMMMMMM   Terminal: gnome-terminal 
            .MMMMMMMMMMMMMMMMMMM      CPU: Intel i7-5600U (4) @ 3.200GHz 
                                      GPU: Intel HD Graphics 5500 
                                      Memory: 6700MiB / 11881MiB 

                                                              

```

**Comment by PolyMeilex** [comment]
Looks like it was not able to find Vulkan capable GPU on the system, do Vulkan examples like `vulcaninfo` or `vkcube` work on your system? ( I believe those are in `vulkan-utils` package)

**Comment by ivy-rew** [comment]
Yes, you are right PolyMailex just tried `vulkaninfo` on my machine:

```lordeagle@le-T450s:~/Downloads$ vulkaninfo
===========
VULKAN INFO
===========

Vulkan Instance Version: 1.1.70

Cannot create Vulkan instance.
/build/vulkan-UL09PJ/vulkan-1.1.70+dfsg1/demos/vulkaninfo.c:768: failed with VK_ERROR_INCOMPATIBLE_DRIVER
```

**Comment by PolyMeilex** [comment]
As far as I know `Intel HD Graphics 5500` should support vulkan without any problems, perhaps you are missing some vulkan related drivers/libs (not sure how mesa vulkan works under mint and ubuntu)

**Comment by PolyMeilex** [comment]
Are those available in your repos `mesa-vulkan-drivers` `mesa-vulkan-drivers:i386`
?

**Comment by ivy-rew** [comment]
Thanks PolyMeilex, I just ran `sudo apt install mesa-vulkan-drivers` and Neothesia shows up and plays my Midi. Very cool !
https://askubuntu.com/questions/1096986/how-to-install-vulcan-for-intel-graphics-card

**Comment by ivy-rew** [comment]
No issue in Neothesia : can be solved by adding mesa-vulkan-drivers to the system.

**Comment by PolyMeilex** [comment]
Grate to hear that 👌
