### ISSUE TITLE
Neothesia crashes at start

### ISSUE THREAD

**Issue by DenpaBorisu** [PolyMeilex/Neothesia#9]
Hello, I tried running Neothesia on my computer it crashes everytime, I even compiled it myself, it still crashes
The window decorations show for like half a second then it closes
I tried running the windows version on wine, it crashes at the start too

My system:
AMD Ryzen 5 2500U
Radeon Vega Mobile Gfx (8)
Ubuntu 20.04 with KDE on x11
Kernel: 5.12.0-051200-lowlatency 
Mesa 21.1.0

The error message:

```
[2021-07-13T03:03:19Z INFO  neothesia::wgpu_jumpstart::gpu] Using AMD RADV RAVEN (ACO) (Vulkan, Prefered Format: Some(Bgra8UnormSrgb))
wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 2, Vulkan)>`
    In a set_scissor_rect command
    Invalid ScissorRect parameters


thread 'main' panicked at 'Handling wgpu errors as fatal by default', /home/boris/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.8.1/src/backend/direct.rs:1955:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Segmentation fault
```

The error I get on wine running the Windows version:

```
55:err:vkd3d_load_vk_instance_procs: Could not get instance proc addr for 'vkGetPhysicalDeviceFragmentShadingRatesKHR'.
55:err:vkd3d_instance_init: Failed to load instance procs, hr 0x80004005.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AdapterRequest', src\lib.rs:50:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

I dont know what additional info to submit or how to run neothesia with `RUST_BACKTRACE=1` environment variable

**Comment by PolyMeilex** [comment]
Hi, thanks for detailed report, I have never seen this one before on my GPU.
Actually, Neothesia does not use `set_scissor_rect` anywhere, so it's probably a problem inherited from one of the libraries that I'm using.
Wine issue seems to be completely unrelated, for some reason it can't find a compatible GPU, and to be hones I don't care, I would rather fix native Linux build (although on my setup it does work in wine)

As I can't reproduce this in any way on my setup, wold you be willing to spend a little bit of time on trying to pinpoint the issue?

For example, my first suspects would be a font drawing library and UI library, so I would appreciate if you could test it's examples, and let me know if those work: 
(like so)
```sh
git clone https://github.com/hecrj/iced.git
cd iced/examples/tour/ 
cargo run
```

**Comment by DenpaBorisu** [comment]
Hello, thanks for the reply
I compiled the Iced tour thing, everything worked well, no error messages or any glitch 
![Iced tourtest](https://user-images.githubusercontent.com/22583225/125469608-a8ad2670-3db0-4c33-a11b-7b6484ee4fe1.png)

**Comment by PolyMeilex** [comment]
Ok, that's good, so It's probably in Neothesia.
Could you send your full Neothesia debug log?
You can enable it like so:
`RUST_LOG=info RUST_BACKTRACE=1 cargo run`

**Comment by DenpaBorisu** [comment]
Yes, here is the backtrace
[neothesia backtrace.txt](https://github.com/PolyMeilex/Neothesia/files/6810154/neothesia.backtrace.txt)

**Comment by PolyMeilex** [comment]
I'm not sure what's causing the problem, but it originates from Iced, not sure why this problem does not manifest in tour example. 
As a rule of thumb, I update iced to the newest version  (it's available on Neothesia's master branch, you can check if that did anything)

From backtrace you gave me, I see that Neothesia fails as soon as it tries to draw its logo in main menu, so I temporarily disabled logo drawing in [no-logo](https://github.com/PolyMeilex/Neothesia/tree/no-img) branch, you can also check if that did anything.  

Sorry for asking you for everything, but as I said I have no way to reproduce this, so I have to rely on your help

**Comment by PolyMeilex** [comment]
That's great, thank you. I still don't know what's wrong, but at least you can run it. I'll try to find a cause, and if I stable upon something, I will let you know.

**Comment by NGStaph** [comment]
Not sure if a ought to create a new issue for this, so I'm adding my crash (on launch) details here.

```
RUST_BACKTRACE=full neothesia
thread 'main' panicked at 'Error in Surface::configure: Validation Error

Caused by:
    Parent device is lost
', /home/jaym/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.1/src/backend/direct.rs:734:18
stack backtrace:
   0:     0x55d9a21fcbc1 - <unknown>
   1:     0x55d9a2224d3f - <unknown>
   2:     0x55d9a21f9e81 - <unknown>
   3:     0x55d9a21fc9d5 - <unknown>
   4:     0x55d9a21fde77 - <unknown>
   5:     0x55d9a21fdc64 - <unknown>
   6:     0x55d9a21fe32c - <unknown>
   7:     0x55d9a21fe227 - <unknown>
   8:     0x55d9a21fcff6 - <unknown>
   9:     0x55d9a21fdf72 - <unknown>
  10:     0x55d9a19c9743 - <unknown>
  11:     0x55d9a1fbac7c - <unknown>
  12:     0x55d9a1fbc2eb - <unknown>
  13:     0x55d9a1fc9ae3 - <unknown>
  14:     0x55d9a1f3b031 - <unknown>
  15:     0x55d9a1f2ac11 - <unknown>
  16:     0x55d9a1a121b9 - <unknown>
  17:     0x55d9a19e12e8 - <unknown>
  18:     0x55d9a19d5673 - <unknown>
  19:     0x55d9a19d5959 - <unknown>
  20:     0x55d9a21f3f45 - <unknown>
  21:     0x55d9a19e18e5 - <unknown>
  22:     0x7f1c0fb58cd0 - <unknown>
  23:     0x7f1c0fb58d8a - __libc_start_main
  24:     0x55d9a19c9ea5 - <unknown>
  25:                0x0 - <unknown>
warning: queue 0x55d9a330ce70 destroyed while proxies still attached:
  wl_buffer@41 still attached
  wl_buffer@40 still attached
  wl_buffer@38 still attached
  wl_buffer@39 still attached
  wl_subsurface@33 still attached
  wl_surface@32 still attached
  wl_subsurface@31 still attached
  wl_surface@30 still attached
  wl_subsurface@29 still attached
  wl_surface@28 still attached
  wl_subsurface@27 still attached
  wl_surface@26 still attached
  wl_subsurface@25 still attached
  wl_surface@24 still attached
  xdg_wm_base@22 still attached
  xdg_activation_v1@14 still attached
  zwp_text_input_manager_v3@13 still attached
  zwp_pointer_constraints_v1@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  wl_seat@10 still attached
  wp_fractional_scale_manager_v1@9 still attached
  wp_viewporter@8 still attached
  wl_subcompositor@7 still attached
  wl_output@6 still attached
  wl_shm@5 still attached
  wl_compositor@4 still attached
  wl_registry@2 still attached
```

my system details are:

- i7-9750h
- GPUs (UHD Graphics 630 + NVIDIA GeForce GTX 1660 Ti Mobile)
- Arch Linux (Kernel: 6.5.6-arch2-1)
